# Generated by Django 5.0.1 on 2024-02-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_created_at_category_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='created',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
