# Generated by Django 5.0.1 on 2024-02-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_options_remove_category_is_sub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
