# Generated by Django 5.0.2 on 2024-02-18 03:15

import galleryfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_options_remove_product_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='album',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage'),
        ),
    ]
