# Generated by Django 5.0.2 on 2024-02-18 03:28

import galleryfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleryproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images', galleryfield.fields.GalleryField(target_model='galleryfield.BuiltInGalleryImage')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='album',
        ),
    ]
