# Generated by Django 5.0.2 on 2024-02-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_mygallery_delete_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyGallery',
        ),
    ]
