# Generated by Django 4.2.10 on 2024-04-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
