# Generated by Django 5.0.2 on 2024-03-04 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0021_delete_mygallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.feature'),
        ),
    ]
